---
- name: Update Raspberry Pi Packages
  hosts: pis
  tasks:
  - name: Update and Upgrade
    become: yes
    apt:
      update_cache: yes
      cache_valid_time: 86400 
      upgrade: yes

- name: Update Mac Packages
  hosts: macs
  tasks:
  - name: Update and upgrade
    community.general.homebrew:
      update_homebrew: yes
      upgrade_all: yes
