set hlsearch
set ignorecase
set incsearch
set number
set noswapfile
set expandtab
set tabstop=2
set shiftwidth=2
set shiftround
set nocompatible
set backspace=indent,eol,start
set showmode
set hidden
set syntax=on
colorscheme slate

source ~/.config/vim/vim-commentary.vim
source ~/.config/vim/vim-fugitive.vim
source ~/.config/vim/vim-plugin.vim
source ~/.config/vim/vim-taskpaper.vim
source ~/.config/vim/keys.vim

